### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by sitano** [intech/TicTacToe#1]
Server, index.js:

is:
    socket.on('step', function (gameId, id) {
        if(Game.games[gameId] !== undefined) return;

should be:
    socket.on('step', function (gameId, id) {
        if(Game.games[gameId] === undefined) return;

Client:
- index.html contains references to game/public, but all the stuff is laying inside ${basedir}/public

**Comment by intech** [comment]
Thanks! index.js fixed this commit 42286857
